theme: jekyll-theme-cayman
title: XploreTV2GO Convention
github:
  is_project_page: true
description: An overview of definitions and specifications for the use of the XploreTV framework in harmonised form for 3rd party services.
