theme: jekyll-theme-cayman
title: XploreTV2GO Convention
github:
  is_project_page: true
description: An overview of best practices, definitions and specifications for the use of 3rd party services within XploreTV.
