theme: jekyll-theme-cayman
title: XploreTV2GO
github:
  is_project_page: true
description: An convention and overview of best practices, definitions and specifications for the use of 3rd party services within XploreTV.
